export const images = [
	{
		id: 1,
		source: './src/img/static/products/Cart1.webp',
		hover: './src/img/static/products/Cart1hover.webp',
		cart: './src/img/static/products/cart1-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 7 x$2.13',
		sizes: 'S',
	},
	{
		id: 2,
		source: './src/img/static/products/cart2-product.webp',
		hover: './src/img/static/products/cart2-hover.webp',
		cart: './src/img/static/products/cart2-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 4 x$4.67',
		sizes: 'XL',
	},
	{
		id: 3,
		source: './src/img/static/products/cart3src.webp',
		hover: './src/img/static/products/cart3-hover.webp',
		cart: './src/img/static/products/cart3-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 7 x$2.13',
		sizes: 'XXL',
	},
	{
		id: 4,
		source: './src/img/static/products/cart4-src.webp',
		hover: './src/img/static/products/cart4-hover.webp',
		cart: './src/img/static/products/cart4-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'L',
	},
	{
		id: 5,
		source: './src/img/static/products/cart5-src.webp',
		hover: './src/img/static/products/cart5-hover.webp',
		cart: './src/img/static/products/cart5-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'M',
	},
	{
		id: 6,
		source: './src/img/static/products/cart6-src.webp',
		hover: './src/img/static/products/cart6-hover.webp',
		cart: './src/img/static/products/cart6-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'ML',
	},
	{
		id: 7,
		source: './src/img/static/products/cart7-src.webp',
		hover: './src/img/static/products/cart7-hover.webp',
		cart: './src/img/static/products/cart7-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'Xl',
	},
	{
		id: 8,
		source: './src/img/static/products/cart8-src.webp',
		hover: './src/img/static/products/cart8-hover.webp',
		cart: './src/img/static/products/cart8-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'XS',
	},
	{
		id: 9,
		source: './src/img/static/products/cart9-src.webp',
		hover: './src/img/static/products/cart9-hover.webp',
		cart: './src/img/static/products/cart9-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'L',
	},
	{
		id: 10,
		source: './src/img/static/products/cart10-src.webp',
		hover: './src/img/static/products/cart10-hover.webp',
		cart: './src/img/static/products/cart10-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'S',
	},
	{
		id: 11,
		source: './src/img/static/products/cart11-src.webp',
		hover: './src/img/static/products/cart11-hover.webp',
		cart: './src/img/static/products/cart11-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'XXL',
	},
	{
		id: 12,
		source: './src/img/static/products/cart12-src.webp',
		hover: './src/img/static/products/cart12-hover.webp',
		cart: './src/img/static/products/cart12-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'ML',
	},
	{
		id: 13,
		source: './src/img/static/products/cart13-src.webp',
		hover: './src/img/static/products/cart13-hover.webp',
		cart: './src/img/static/products/cart13-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'M',
	},
	{
		id: 14,
		source: './src/img/static/products/cart14-src.webp',
		hover: './src/img/static/products/cart14-hover.webp',
		cart: './src/img/static/products/cart14-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'L',
	},
	{
		id: 15,
		source: './src/img/static/products/cart15-src.webp',
		hover: './src/img/static/products/cart15-hover.webp',
		cart: './src/img/static/products/cart15-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'XS',
	},
	{
		id: 16,
		source: './src/img/static/products/cart16-src.webp',
		hover: './src/img/static/products/cart16-hover.webp',
		cart: './src/img/static/products/cart16-cart.webp',
		text: 'Black T-shirt with white stripes',
		Price: '14.90',
		subText: 'or 9 x$1.21',
		sizes: 'XL',
	},
];

export const buttons = [
	{
		name: 'All',
		value: 'all',
	},
	{
		name: 'XS',
		value: 'XS',
	},
	{
		name: 'S',
		value: 'S',
	},
	{
		name: 'M',
		value: 'M',
	},
	{
		name: 'ML',
		value: 'ML',
	},
	{
		name: 'L',
		value: 'L',
	},
	{
		name: 'XL',
		value: 'XL',
	},
	{
		name: 'XXL',
		value: 'XXL',
	},
];
